# Gradle
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# 项目路径含非 ASCII 字符（中文目录），跳过 AGP 路径检查
android.overridePathCheck=true

# Kotlin
kotlin.code.style=official
